name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:   
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: mkdir ./test/database
    - run: npm run build --if-present

    - name: Generate E2E test files list
      id: generate-files
      run: |
        FILES=$(find ./test/e2e -name '*.e2e-spec.ts')
        echo "::set-output name=test_files::$FILES"

    - name: Set test matrix
      run: |
        echo "test-file=${{ steps.generate-files.outputs.test_files }}" >> $GITHUB_ENV

    - name: Run E2E Test ${{ matrix.test-file }}
      run: |
        npm run test:e2e -- --runTestsByPath ${{ matrix.test-file }}
