name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        test-file: 
          - './test/e2e/auth.e2e-spec.ts'
          - './test/e2e/users.e2e-spec.ts'
          - './test/e2e/category.e2e-spec.ts'
          - './test/e2e/subcategory.e2e-spec.ts'
          - './test/e2e/tag.e2e-spec.ts'

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:   
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: mkdir ./test/database
    - run: npm run build --if-present

    - name: Run E2E Test ${{ matrix.test-file }}
      run: |
        npm run test:e2e -- --runTestsByPath ${{ matrix.test-file }}
